mobi.QualityControl/mobi.QualityControl.Web/ViewModels/JobSet/JobSetEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mobi.QualityControl.Web.Models;

namespace Mobi.QualityControl.Web.ViewModels.JobSet
{
    public class JobSetEditModel :IViewModel
    {
        public JobSetEditModel()
        {
            JobSetQuestionSets = new List<JobSetQuestionSet>();
            QuestionSetListItems = new List<SelectListItem>();
            JobSetJobsItemModels = new List<JobSetJobsItemModel>();
        }

        public Guid JobSetId { get; set; }
        public string JobSetName { get; set; }
        public List<JobSetQuestionSet> JobSetQuestionSets { get; set; }
        public ScreenType ScreenType { get; set; }
        public List<SelectListItem> QuestionSetListItems { get; set; }
        public List<JobSetJobsItemModel> JobSetJobsItemModels { get; set; }
        
    }

    public class AddQuestionSetModel
    {
        public Guid JobSetId { get; set; }
        public Guid QuestionSetId { get; set; }
    }

    public class JobSetQuestionSet
    {
        public Guid QuestionSetId { get; set; }
        public string QuestionSetName { get; set; }

    }

    public class JobSetJobsItemModel
    {
        public Guid JobId { get; set; }
        public string JobReference { get; set; }
    }
}

mobi.QualityControl/mobi.QualityControl.Web/ViewModels/JobSet/JobSetIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mobi.QualityControl.Web.ViewModels.JobSet
{
    public class JobSetIndexModel
    {
        public JobSetIndexModel()
        {
            JobSetIndexItems = new List<JobSetIndexItem>();
        }
        public List<JobSetIndexItem> JobSetIndexItems { get; set; }
    }

    public class JobSetIndexItem
    {
        public Guid JobSetId { get; set; }
        public string JobSetName { get; set; }
    }
}

mobi.QualityControl/mobi.QualityControl.Web/ViewModels/JobSet/StartJobModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mobi.QualityControl.Web.ViewModels.JobSet
{
    public class StartJobModel
    {
        public Guid JobSetId { get; set; }
        public String JobReference { get; set; }
    }
}

mobi.QualityControl/mobi.QualityControl.Web/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mobi.QualityControl.Framework.DataContext;
using Mobi.QualityControl.Web.Models;
using Mobi.QualityControl.Web.ViewModels.Job;

namespace Mobi.QualityControl.Web.Controllers
{
    public class JobController : Controller
    {
        private QcContext _context = new QcContext();
        //
        // GET: /Job/
        public ActionResult Details(Guid jobId)
        {
            var model = PopulateJobEditModel(jobId);
            model.ScreenType = ScreenType.Details;
            return View(model);
        }


        public JobEditModel PopulateJobEditModel(Guid id)
        {
            var model = new JobEditModel();
            var jobQuery = _context.Jobs.Select(o => new
            {
                o.JobId,
                o.Jobcode,
                TransactionSets = o.TransactionSets.Select(ts => new
                {
                  ts.TransactionSetId,
                  ts.IsFullyComplete,
                  ts.IsEntryComplete,
                  ts.CreatedDate
                })
            }).FirstOrDefault(o => o.JobId == id);

            foreach (var transactionSet in jobQuery.TransactionSets)
            {
                model.JobTransactionSetItems.Add(new JobTransactionSetItem()
                {
                    TransactionSetId = transactionSet.TransactionSetId,
                    TransRef = transactionSet.CreatedDate.ToShortDateString()
                });
            }

            return model;

        }
	}
}

mobi.QualityControl/mobi.QualityControl.Web/Controllers/JobSetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Mobi.QualityControl.Framework.DataContext;
using Mobi.QualityControl.Framework.Helpers;
using Mobi.QualityControl.Framework.Model;
using Mobi.QualityControl.Web.Models;
using Mobi.QualityControl.Web.ViewModels.JobSet;

namespace Mobi.QualityControl.Web.Controllers
{
    public class JobSetController : AuthenticatedController
    {

        private QcContext _context = new QcContext();
        //
        // GET: /JobSet/
        public ActionResult Index()
        {
            var model = new JobSetIndexModel();
            var companyId = AuthenticatedUser.Company.CompanyId;
            var jobsetQuery = _context.JobSets.Select(o => new {o.JobSetId, o.JobSetName, o.Company.CompanyId, o.IsDeleted}).Where(o => o.CompanyId == companyId && !o.IsDeleted);

            foreach (var jobset in jobsetQuery)
            {
                model.JobSetIndexItems.Add(new JobSetIndexItem()
                {
                    JobSetId = jobset.JobSetId,
                    JobSetName = jobset.JobSetName
                });
            }


            return View(model);
        }

        public ActionResult Create()
        {
            var model = new JobSetEditModel();
            model.ScreenType = ScreenType.Create;
            return View("Edit", model);
        }

        public ActionResult Details(Guid id)
        {
            var model = new JobSetEditModel();
            model.ScreenType = ScreenType.Details;
            model.JobSetId = id;
            PopulateEditModel(model);
            return View("Edit", model);
        }

        public ActionResult Edit(Guid id)
        {
            var model = new JobSetEditModel();
            model.ScreenType = ScreenType.Edit;
            model.JobSetId = id;
            PopulateEditModel(model);
            return View("Edit", model);
        }

        [HttpPost]
        public ActionResult Edit(JobSetEditModel model)
        {
            if (model.ScreenType == ScreenType.Create)
            {
                var existingQuestionSet = _context.JobSets.Select(o => new
                {
                    o.JobSetId,
                    o.Company.CompanyId,
                    o.JobSetName
                }).FirstOrDefault(o => o.CompanyId == this.AuthenticatedUser.Company.CompanyId && o.JobSetName == model.JobSetName);
                if (existingQuestionSet != null)
                {
                    ModelState.AddModelError("", "Job Set Already Exists");
                }
            }
            else
            {
                var existingQuestionSet = _context.JobSets.Select(o => new
                {
                    o.JobSetId,
                    o.Company.CompanyId,
                    o.JobSetName
                }).FirstOrDefault(o => o.CompanyId == this.AuthenticatedUser.Company.CompanyId && o.JobSetName == model.JobSetName && o.JobSetId != model.JobSetId);
                if (existingQuestionSet != null)
                {
                    ModelState.AddModelError("", "Job Set Already Exists");
                }
            }

              var jobSetId = model.JobSetId;
            if (ModelState.IsValid)
            {
                JobSet jobSet;
                if (model.ScreenType == ScreenType.Create)
                {
                    jobSet = new JobSet();
                    jobSet.JobSetId = Guid.NewGuid();
                    jobSetId = jobSet.JobSetId;
                }
                else
                {
                    jobSet = _context.JobSets.FirstOrDefault(o => o.JobSetId == model.JobSetId && o.Company.CompanyId == this.AuthenticatedUser.Company.CompanyId);
                }
                jobSet.JobSetName = model.JobSetName;
               
                if (model.ScreenType == ScreenType.Create)
                {
                    jobSet.Company = _context.Companies.FirstOrDefault(o => o.CompanyId == AuthenticatedUser.Company.CompanyId);
                    _context.JobSets.Add(jobSet);
                }
                _context.SaveChanges();
                TempData["SuccessMessage"] = "The Job Set has been successfully updated.";
                return RedirectToAction("Edit", new { id = jobSetId });
            }
            model.QuestionSetListItems = new DropDownHelper().GetQuestionSetDropDown(AuthenticatedUser.Company.CompanyId);
            return View("Edit", model);
        }

        private void PopulateEditModel(JobSetEditModel model)
        {
            var jobsetQuery = _context.JobSets.Select(o => new
            {
                o.JobSetId,
                o.JobSetName,
                QuestionSets = o.QuestionSets.Select(q => new
                {
                    q.QuestionSetId,
                    q.QuestionSetName
                }),
                Jobs = o.Jobs.Select(j => new
                {
                    j.JobId,
                    j.Jobcode
                })
            }).FirstOrDefault(o => o.JobSetId == model.JobSetId);
            if (jobsetQuery != null)
            {
                model.JobSetName = jobsetQuery.JobSetName;

                foreach (var questionSet in jobsetQuery.QuestionSets)
                {
                    model.JobSetQuestionSets.Add(new JobSetQuestionSet()
                    {
                        QuestionSetId = questionSet.QuestionSetId,
                        QuestionSetName = questionSet.QuestionSetName
                    });
                }

                foreach (var job in jobsetQuery.Jobs)
                {
                    model.JobSetJobsItemModels.Add(new JobSetJobsItemModel()
                    {
                        JobId = job.JobId,
                        JobReference = job.Jobcode
                    });
                }
            }
            model.QuestionSetListItems = new DropDownHelper().GetQuestionSetDropDown(AuthenticatedUser.Company.CompanyId);
        }

        [HttpPost]
        public ActionResult AddQuestionSet(AddQuestionSetModel model)
        {
            var jobSet = _context.JobSets.FirstOrDefault(o => o.JobSetId == model.JobSetId);
            if (jobSet != null)
            {
                var questionSet = _context.QuestionSets.FirstOrDefault(o => o.QuestionSetId == model.QuestionSetId);
                if (questionSet != null)
                {
                    jobSet.QuestionSets.Add(questionSet);
                }

                TempData["SuccessMessage"] = "The question set has been successfully created.";
                _context.SaveChanges();

            }
            return RedirectToAction("Edit", "JobSet", new {id = model.JobSetId});
        }

        public ActionResult StartJob(Guid id)
        {
            var model = new StartJobModel();
            model.JobSetId = id;
            return View(model);
        }

        [HttpPost]
        public ActionResult StartJob(StartJobModel model)
        {
            //get jobset 
            var jobsetQuery = _context.JobSets.FirstOrDefault(o => o.JobSetId == model.JobSetId);
            var job = new Job();
            job.JobId = Guid.NewGuid();
            job.Jobcode = model.JobReference;
            jobsetQuery.Jobs.Add(job);
            _context.SaveChanges();
            
            //loop through each question set
            foreach (var questionset in jobsetQuery.QuestionSets)
            {
               var transSet =  new TransactionHelper().CreateTransactionSet(questionset.QuestionSetId);
                transSet.Job.JobId = job.JobId;
                _context.SaveChanges();
            }
            _context.SaveChanges();
           
            return View(model);
        }


        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }
	}
}

mobi.QualityControl/mobi.QualityControl.Web/Views/JobSet/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}



@using Mobi.QualityControl.Web.Models
@model Mobi.QualityControl.Web.ViewModels.JobSet.JobSetEditModel



<div class="page-title">
    <a href="@Url.Action("Index","Dashboard")"> <i class="icon-custom-left"></i></a>
    <h3>@ViewBag.Title</h3>
    @if (Model.ScreenType == ScreenType.Details)
    {
        <div class="pull-right">
            <a href="@Url.Action("Edit", "JobSet", new {area = "", id = Model.JobSetId})" class="btn btn-primary "><i></i>Edit</a>
        </div>
    }
</div>

@using (Html.BeginForm("Edit", "JobSet", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.ScreenType)

    <div class="row">
        <div class="col-md-6">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4>Job Set</h4>
                    <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row form-row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.JobSetName, new { @class = "form-label" })
                                <span class="help">&nbsp;</span>
                                <div class="controls">
                                    @Html.TextBoxFor(model => model.JobSetName, new { @class = "form-control" })
                                </div>
                            </div>

                        </div>

                    </div>
                    @if (Model.ScreenType != ScreenType.Details)
                    {
                        <div class="form-actions">
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-cons"><i class="icon-ok"></i> Save</button>
                                <button type="button" class="btn btn-white btn-cons">Cancel</button>
                            </div>
                        </div>
                    }
                </div>
            </div>

        </div>

        @if (Model.ScreenType != ScreenType.Create)
        {

            <div class="col-md-6">
                <div class="grid simple">
                    <div class="grid-title no-border">
                        <h4>Question Set Rules</h4>
                        <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
                    </div>
                    <div class="grid-body no-border">
                        <div class="row">
                            @if (Model.ScreenType != ScreenType.Details)
                            {
                                <div class="widget-body">
                                    <div class="buttons pull-right">
                                        <button class="btn btn-lg btn-primary" data-toggle="modal" data-target="#addQuestionSet"> Add Question Set </button>

                                    </div>
                                </div>
                            }
                            @if (Model.JobSetQuestionSets.Count > 0)
                            {
                                <div class="col-md-8 col-sm-8 col-xs-8">
                                    <table class="table table-striped table-bordered table-white table-responsive swipe-horizontal table-primary">
                                        <thead>
                                            <tr>

                                                <th>
                                                    JobSet
                                                </th>

                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.JobSetQuestionSets)
                                            {
                                                <tr class="selectable">
                                                    <td>
                                                        @item.QuestionSetName
                                                    </td>
                                                    <td>
                                                        <a href="@Url.Action("DeleteQuestionSetLink", "Jobset", new {area = "", id = Model.JobSetId, questionSetId = item.QuestionSetId}) " class=" btn btn-sm btn-small btn-danger">Delete</a>
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            }
                            else
                            {
                                <div class="alert">
                                    <button class="close" data-dismiss="alert"></button>
                                    No Job Sets Rules Exist
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="grid simple">
                    <div class="grid-title no-border">
                        <h4>Question Set Rules</h4>
                        <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
                    </div>
                    <div class="grid-body no-border">
                        <div class="row">


                            @if (Model.JobSetJobsItemModels.Count > 0)
                            {

                                <div class="col-md-8 col-sm-8 col-xs-8">
                                    <table class="table table-striped table-bordered table-white table-responsive swipe-horizontal table-primary">
                                        <thead>
                                            <tr>

                                                <th>
                                                    JobSet
                                                </th>

                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.JobSetJobsItemModels)
                                            {
                                                <tr class="selectable">
                                                    <td>
                                                        @item.JobReference
                                                    </td>
                                                    <td>
                                                        <a href="@Url.Action("Details", "Job", new {area = "", jobId = item.JobId})" class=" btn btn-sm btn-small btn-cons">View</a>
                                                        
                                                    </td>
                                                </tr>

                                            }
                                        </tbody>
                                    </table>
                                </div>
                            }
                            else
                            {
                                <div class="alert">
                                    <button class="close" data-dismiss="alert"></button>
                                    No Jobs Exist
                                </div>
                            }

                        </div>

                    </div>
                </div>



            </div>
                    <!-- END BASIC FORM ELEMENTS-->
        }
    </div>
    if (Model.ScreenType == ScreenType.Edit)
    {
        @Html.HiddenFor(model => model.JobSetId)
    }
}








<div>
    @Html.ActionLink("Back to List", "Index", "JobSet", new { @class = "btn btn-white btn-cons" })
</div>





<div class="modal fade" id="addQuestionSet" tabindex="-1" role="dialog" aria-labelledby="addQuestionSetLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <br>
                <h4 id="myModalLabel" class="semi-bold">Add Question Set</h4>
                <br>
            </div>
            @using (Html.BeginForm("AddQuestionSet", "JobSet", FormMethod.Post))
            {
                <div class="modal-body">
                    <div class="row form-row">
                        <div class="col-md-8">
                            @Html.DropDownList("QuestionSetId", Model.QuestionSetListItems)
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Save Changes" />
                </div>
                @Html.HiddenFor(m => m.JobSetId)

            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>








@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @if (Model.ScreenType == ScreenType.Details)
    {
        <script type="text/javascript">

            $("input").prop('disabled', true);
        </script>
    }
}


mobi.QualityControl/mobi.QualityControl.Web/Views/JobSet/Index.cshtml
@model Mobi.QualityControl.Web.ViewModels.JobSet.JobSetIndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}

<!-- Heading -->
<div class="page-title">
    <a href="@Url.Action("Index","Dashboard")"><i class="icon-custom-left"></i></a>
    <h3>Job Sets</h3>
    <div class="buttons pull-right">
        <a href="@Url.Action("Create", "JobSet", new { area = "" })" class="btn btn-primary btn-icon glyphicons circle_plus"><i></i>Add Job Set</a>
    </div>
    <div class="clearfix"></div>
</div>

<!-- // Heading END -->

<div class="row-fluid">
    <div class="span12">
        <div class="grid simple ">
            <div class="grid-title">
                <h4>Job Set</h4>
                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            <div class="grid-body ">
                @if (Model.JobSetIndexItems.Count > 0)
                {
                    <table class="table table-hover table-condensed" id="example">
                        <thead>
                            <tr>
                                <th></th>
                                <th>
                                    Job Set
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.JobSetIndexItems)
                            {
                                <tr class="selectable">
                                    <td></td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.JobSetName)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Details", "jobSet", new {area = "", id = item.JobSetId})" class=" btn btn-primary btn-sm .btn-small ">View</a>
                                        <a href="@Url.Action("Delete", "JobSet", new {area = "", id = item.JobSetId})" class=" btn btn-sm .btn-small btn-danger">Delete</a>
                                        <a href="@Url.Action("StartJob", "JobSet", new {area = "", id = item.JobSetId})" class=" btn btn-primary btn-sm .btn-small ">Start Job</a>
                                   </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert">
                        <button class="close" data-dismiss="alert"></button>
                        No Job Sets Exist
                    </div>
                }

            </div>
        </div>
    </div>
</div>

mobi.QualityControl/mobi.QualityControl.Web/Views/JobSet/StartJob.cshtml
@model Mobi.QualityControl.Web.ViewModels.JobSet.StartJobModel
@{
    ViewBag.Title = "StartJob";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}




<div class="page-title">
    <a href="@Url.Action("Index","JobSet", new {id = Model.JobSetId})"> <i class="icon-custom-left"></i></a>
    <h3>@ViewBag.Title</h3>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.JobSetId)
    <!-- Row -->
    <div class="row">
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4>Question </h4>
                    <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row form-row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.JobReference, new { @class = "form-label" })
                                <span class="help">&nbsp;</span>
                                <div class="controls">
                                    @Html.TextBoxFor(model => model.JobReference, new { @class = "form-control" })

                                </div>

                            </div>
                        </div>
                    </div>
                    @Html.ValidationSummary()
                    <div class="form-actions">
                        <div class="pull-right">
                            <button type="submit" class="btn btn-success btn-cons"><i class="icon-ok"></i> Save</button>
                            <button type="button" class="btn btn-white btn-cons">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



}