mobi.QualityControl/mobi.QualityControl.Web/ViewModels/ControlList/ControlListEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using Mobi.QualityControl.Web.Models;

namespace Mobi.QualityControl.Web.ViewModels.ControlList
{
    public class ControlListEditModel : IViewModel
    {
        public Guid ControlListId { get; set; }
        [Display(Name = "Control List Name")]
        public string ControlListName { get; set; }

        public List<ControlListModelItem> ControlListModelItems { get; set; }

        public ControlListEditModel()
        {
            ControlListModelItems = new List<ControlListModelItem>();
        }

        public ScreenType ScreenType { get; set; }
        public bool HasImages { get; set; }

    }

    public class ControlListModelItem
    {
        public Guid ControlListItemId { get; set; }
        public Guid ControlListId { get; set; }
        public string ItemName { get; set; }
        public string ImageUrl {get;set;}
        public HttpPostedFileBase UploadFile { get; set; }

    }
}

mobi.QualityControl/mobi.QualityControl.Web/ViewModels/ControlList/ControlListImportModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mobi.QualityControl.Web.ViewModels.ControlList
{
    public class ControlListImportModel
    {
        public HttpPostedFileBase ExcelFile { get; set; }
        public bool IsNew { get; set; }
        public bool DeleteMissing { get; set; }
        public Guid ControlListId { get; set; }
        
    }

    public class ImportListItem
    {
        public string Name { get; set; }
        public string Value { get; set; }
        
    }
}

mobi.QualityControl/mobi.QualityControl.Web/ViewModels/ControlList/ControlListIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mobi.QualityControl.Web.ViewModels.ControlList
{
    public class ControlListIndexModel 
    {
        public List<ControlListIndexItem> ControlListIndexItems { get; set; }

        public ControlListIndexModel()
        {
            ControlListIndexItems = new List<ControlListIndexItem>();
        }
        
    }

    public class ControlListIndexItem
    {
        public Guid ControlListId { get; set; }
        public string ControlListName { get; set; }
        public int ItemCount { get; set; }
    }
}

mobi.QualityControl/mobi.QualityControl.Web/Controllers/ControlListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using log4net;
using Mobi.QualityControl.Framework.DataContext;
using Mobi.QualityControl.Framework.Helpers;
using Mobi.QualityControl.Framework.Model;
using Mobi.QualityControl.Web.Models;
using Mobi.QualityControl.Web.ViewModels.ControlList;
using OfficeOpenXml;

namespace Mobi.QualityControl.Web.Controllers
{
    [Authorize]
    public class ControlListController : AuthenticatedController
    {

        ILog _log = LogManager.GetLogger(typeof(ControlListController));

        //
        // GET: /ControlList/
        private QcContext _context = new QcContext();

        public ActionResult Index()
        {
            var model = new ControlListIndexModel();

            var controlListQuery = _context.ControlLists.Select(o => new
            {
                o.IsDeleted,
                o.ControlListId,
                o.ControlListName,
               ListCount =  o.ControlListItems.Count
            }).Where(o => !o.IsDeleted);
            foreach (var controlList in controlListQuery.ToList())
            {
                model.ControlListIndexItems.Add(new ControlListIndexItem
                {
                    ControlListId = controlList.ControlListId,
                    ControlListName = controlList.ControlListName,
                    ItemCount = controlList.ListCount
                });
            }
            return View(model);
        }

        

        public ActionResult Details(Guid id)
        {
            var model = new ControlListEditModel();
            model.ScreenType = ScreenType.Details;
            PopulateEditModel(id, model);
            return View("Edit", model);
        }


        public ActionResult Create()
        {
            var model = new ControlListEditModel();
            model.ScreenType = ScreenType.Create;
            return View("Edit", model);
        }

        public ActionResult Edit(Guid id)
        {
            var model = new ControlListEditModel();
            model.ScreenType = ScreenType.Edit;
            PopulateEditModel(id, model);

            return View(model);
        }

        [HttpPost]
        public ActionResult ImportNew(ControlListImportModel model)
        {
            var excelFile = HttpContext.Request.Files[0];
            if (excelFile != null)
            {
                var excelPackage = new ExcelPackage(excelFile.InputStream);
                var importItems = new List<ImportListItem>();
                var worksheet = excelPackage.Workbook.Worksheets[1];
                var rowCount = worksheet.Dimension.End.Row + 1;

                var controlList = _context.ControlLists.FirstOrDefault(o => o.ControlListId == model.ControlListId);

                for (int i = 1; i < rowCount; i++)
                {

                    if (worksheet.Cells[i, 1].Value != null)
                        importItems.Add(new ImportListItem
                        {
                   
                            Value = worksheet.Cells[i,1].Value.ToString()
                        });
                }

                foreach (var importListItem in importItems)
                {
                    if (controlList != null)
                    {
                        var existingItem = controlList.ControlListItems.FirstOrDefault(o => o.ControlValue == importListItem.Value);
                        if (existingItem == null)
                        {
                            var controlListItem = new ControlListItem();
                            controlListItem.ControlListItemId = Guid.NewGuid();
                            controlListItem.ControlValue = importListItem.Value;
                            controlList.ControlListItems.Add(controlListItem);
                        }
                    }
                }
            }

            _context.SaveChanges();
            TempData["SuccessMessage"] = "Item Saved";

            return RedirectToAction("Edit", new {id = model.ControlListId});
        }

        private void PopulateEditModel(Guid id, ControlListEditModel model)
        {
            var controlList = _context.ControlLists.Select(o => new
            {
                o.ControlListId,
                o.Company.CompanyId,
                o.ControlListName,
                o.IsDeleted,
                ControlListItems = o.ControlListItems.Select(i => new
                {
                    i.ImageUrl,
                    i.ControlListItemId,
                    i.ControlValue,
                    i.IsDeleted
                })
            }).FirstOrDefault(o => o.ControlListId == id
                                                              && o.CompanyId == AuthenticatedUser.Company.CompanyId
                                                                    && !o.IsDeleted);

            if (controlList != null)
            {
                model.ControlListId = controlList.ControlListId;
                model.ControlListName = controlList.ControlListName;
                foreach (var controlListItem in controlList.ControlListItems.Where(o => !o.IsDeleted))
                {
                    if (controlListItem.ImageUrl != null)
                        model.HasImages = true;
                    model.ControlListModelItems.Add(new ControlListModelItem
                    {
                        ControlListItemId = controlListItem.ControlListItemId,
                        ItemName = controlListItem.ControlValue,
                        ImageUrl = controlListItem.ImageUrl
                    });
                }
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ControlListEditModel model)
        {
            var controlListId = model.ControlListId;
            if (model.ScreenType == ScreenType.Create)
            {
                var existingControlList = _context.ControlLists.FirstOrDefault(o => o.Company.CompanyId == AuthenticatedUser.Company.CompanyId && o.ControlListName == model.ControlListName);
                if (existingControlList != null)
                {
                    ModelState.AddModelError("", "Control List Name Already Exists");
                }

            }
            else
            {
                var existingControlList = _context.ControlLists.FirstOrDefault(o => o.Company.CompanyId == AuthenticatedUser.Company.CompanyId && o.ControlListName == model.ControlListName && o.ControlListId != model.ControlListId);
                if (existingControlList != null)
                {
                    ModelState.AddModelError("", "Control List Name Already Exists");
                }
            }

            if (ModelState.IsValid)
            {
                ControlList controlList;
                if (model.ScreenType == ScreenType.Create)
                {

                    controlList = new ControlList();
                    controlList.ControlListId = Guid.NewGuid();
                    controlListId = controlList.ControlListId;
                }
                else
                {
                    controlList = _context.ControlLists.FirstOrDefault(o => o.ControlListId == model.ControlListId && o.Company.CompanyId == AuthenticatedUser.Company.CompanyId);
                }
                if (controlList != null)
                {
                    controlList.ControlListName = model.ControlListName;

                    if (model.ScreenType == ScreenType.Create)
                    {
                        controlList.Company = _context.Companies.FirstOrDefault(o => o.CompanyId == AuthenticatedUser.Company.CompanyId);
                        _context.ControlLists.Add(controlList);

                    }
                }
                _context.SaveChanges();
                TempData["SuccessMessage"] = "The Control List has been successfully updated.";
                return RedirectToAction("Edit", new { id = controlListId });
            }
            return View(model);
        }

        public ActionResult Delete(Guid id)
        {

            var controlList = _context.ControlLists.FirstOrDefault(o => o.ControlListId == id);
            if (controlList != null)
            {
                controlList.IsDeleted = true;
                controlList.UpdatedDate = DateTime.UtcNow;
                controlList.UpdatedUser = AuthenticatedUser.UserName;
                _context.SaveChanges();
                TempData["SuccessMessage"] = "The ControlList Set " + controlList.ControlListName +
                                             " has successfully been removed";
            }
            else
            {
                TempData["ErrorMessage"] = "There was an issue removing Control List " + controlList.ControlListName;
            }
            return RedirectToAction("Index");
        }

        public ActionResult DeleteItem(Guid id)
        {
            Guid controlListId = Guid.Empty;
            var controlListItem = _context.ControlListItems.FirstOrDefault(o => o.ControlListItemId == id);
            if (controlListItem != null)
            {
                controlListId = controlListItem.ControlList.ControlListId;
                controlListItem.IsDeleted = true;
                controlListItem.UpdatedDate = DateTime.UtcNow;
                controlListItem.UpdatedUser = AuthenticatedUser.UserName;
                _context.SaveChanges();
                TempData["SuccessMessage"] = "The ControlList Item " + controlListItem.ControlValue +
                                             " has successfully been removed";
            }
            else
            {

mobi.QualityControl/mobi.QualityControl.Web/Views/ControlList/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}



@using Mobi.QualityControl.Web.Models
@model Mobi.QualityControl.Web.ViewModels.ControlList.ControlListEditModel



<div class="page-title">
    <a href="@Url.Action("Index","ControlList")">  <i class="icon-custom-left"></i></a>
    <h3>@ViewBag.Title</h3>
    @if (Model.ScreenType == ScreenType.Details)
    {
        <div class="pull-right">
            <a href="@Url.Action("Edit", "ControlList", new {area = "", id = Model.ControlListId})" class="btn btn-primary "><i></i>Edit</a>
        </div>
    }
</div>




<div class="row">
    <div class="col-md-6">
        <div class="grid simple">
            <div class="grid-title no-border">
                <h4>Control List</h4>

                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            @using (Html.BeginForm("Edit", "ControlList", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(m => m.ControlListId)
                @Html.HiddenFor(m => m.ScreenType)
                <div class="grid-body no-border">
                    <br>
                    <div class="row form-row">
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.LabelFor(model => model.ControlListName, new { @class = "form-label" })
                                <span class="help">&nbsp;</span>
                                <div class="controls">
                                    @Html.TextBoxFor(model => model.ControlListName, new { @class = "form-control" })

                                </div>
                            </div>
                        </div>
                        @Html.ValidationSummary(true)
                    </div>
                    @if (Model.ScreenType != ScreenType.Details)
                    {
                        <div class="form-actions">
                            <div class="pull-right">
                                <button type="submit" class="btn btn-success btn-cons"><i class="icon-ok"></i> Save</button>
                                <button type="button" class="btn btn-white btn-cons">Cancel</button>
                            </div>

                        </div>

                    }

                </div>
            }
        </div>
    </div>
    @if (Model.ScreenType != ScreenType.Details)
    {
    <div class="col-md-6">
        <div class="grid simple">
            <div class="grid-title no-border">
                <h4>Import </h4>
                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            <div class="grid-body no-border">
                <div class="row-fluid">
                    @using (Html.BeginForm("ImportNew", "ControlList", FormMethod.Post, new { @class = "dropzone no-margin" }))
                    {

                        <div class="fallback">
                            <input name="ExcelFile" type="file" multiple />
                        </div>
                        @Html.HiddenFor(o => o.ControlListId)
                    }
                </div>
            </div>
        </div>
    </div>
    }
    @if (Model.ScreenType != ScreenType.Create)
    {
        <div class="col-md-12">
            <div class="grid simple">
                <div class="grid-title no-border">
                    <h4>Items</h4>
                    <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
                </div>
                <div class="grid-body no-border">
                    <br>
                    <div class="row">
                        @if (Model.ScreenType != ScreenType.Details)
                        {

                          
                            <div class="widget-body">
                                <div class="buttons pull-right">
                                    <button class="btn btn-lg btn-primary" data-toggle="modal" data-target="#addControlListItem"> Add Control List Item </button>
                                </div>
                            </div>

                                <!-- Modal -->
                            <div class="modal fade" id="addControlListItem" tabindex="-1" role="dialog" aria-labelledby="addControlListItemLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                            <br>
                                            <h4 id="myModalLabel" class="semi-bold">Control List Item</h4>
                                            <br>
                                        </div>
                                        @using (Html.BeginForm("AddControlListItem", "ControlList", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                        {
                                            <div class="modal-body">
                                                <div class="row form-row">
                                                    <div class="col-md-8">
                                                        <input type="text" class="form-control" placeholder="Value" name="ItemName">
                                                    </div>
                                                    <div class="col-md-4">
                                                        <input type="file" class="form-control" placeholder="Image" name="UploadFile" id="UploadFile">
                                                    </div>
                                                </div>

                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                <input type="submit" class="btn btn-primary" value="Save Changes" />
                                            </div>
                                            @Html.HiddenFor(o => o.ControlListId)
                                        }
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                                <!-- /.modal -->
                        }
                        <div class="col-md-8 col-sm-8 col-xs-8">

                            <div class="widget-body">

                                <div class="clearfix"></div>
                                <table class="table table-striped table-bordered table-white table-responsive swipe-horizontal table-primary">
                                    <thead>
                                        <tr>

                                            <th>
                                                Name
                                            </th>
                                            @if(Model.HasImages)
                                            {<th>Image</th>}
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.ControlListModelItems)
                                        {
                                            <tr class="selectable">
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.ItemName)
                                                </td>
                                                @if(Model.HasImages)
                                                {<td>
                                                    <img src="@item.ImageUrl" />
                                                </td>
}
                                                <td>
                                                    
                                                    <a href="@Url.Action("DeleteItem", "ControlList", new { area = "", id = item.ControlListItemId }) " class=" btn btn-sm .btn-small btn-danger">Delete</a>

                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    }


</div>


@if (Model.ScreenType == ScreenType.Edit)
{
    @Html.HiddenFor(model => model.ControlListId)
}









<div>
    @Html.ActionLink("Back to List", "Index", new { @class = "btn btn-white btn-cons" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @if (Model.ScreenType == ScreenType.Details)
    {
        <script type="text/javascript">

            $("input").prop('disabled', true);
        </script>
    }
    else
    {

        <script src="/Content/Admin/plugins/dropzone/dropzone.min.js" type="text/javascript"></script>

    }

}

mobi.QualityControl/mobi.QualityControl.Web/Views/ControlList/Index.cshtml
@model Mobi.QualityControl.Web.ViewModels.ControlList.ControlListIndexModel


<!-- Heading -->
<div class="page-title">
    <a href="@Url.Action("Index","Dashboard")"> <i class="icon-custom-left"></i></a>
    <h3>Control List</h3>
    <div class="buttons pull-right">
        <a href="@Url.Action("Create", "ControlList", new { area = "" })" class="btn btn-primary btn-icon glyphicons circle_plus"><i></i>Add Control List</a>
    </div>
    <div class="clearfix"></div>
</div>

<!-- // Heading END -->

<div class="row">
    <div class="col-md-12">
        <div class="grid simple ">
            <div class="grid-title">
                <h4>Table <span class="semi-bold">Control List</span></h4>
                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            <div class="grid-body ">
                <table class="table table-hover table-condensed" id="example">
                    <thead>
                        <tr>

                            <th>
                                Control List
                            </th>

                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.ControlListIndexItems)
                        {
                            <tr class="selectable">
                                <td>
                                    @Html.DisplayFor(modelItem => item.ControlListName)
                                </td>
                                <td>

                                    <a href=" @Url.Action("Details", "ControlList", new { area = "", id = item.ControlListId }) " class=" btn btn-primary btn-sm btn-small ">View</a>
                                    <a href=" @Url.Action("Delete", "ControlList", new { area = "", id = item.ControlListId }) " class=" btn btn-sm btn-small btn-danger">Delete</a>

                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


            </div>
        </div>

    </div>
   
    
   
</div>