mobi.QualityControl/mobi.QualityControl.Web/ViewModels/Results/ResultViewEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.AccessControl;
using System.Web;
using System.Web.Mvc;
using Mobi.QualityControl.Framework.Enum;
using Mobi.QualityControl.Web.Helpers;
using Mobi.QualityControl.Web.Models;

namespace Mobi.QualityControl.Web.ViewModels.Results
{
    public class ResultViewEditModel : IViewModel
    {
        public Guid QuestionSetId { get; set; }
        public string QuestionSetName { get; set; }
        public Guid ResultViewId { get; set; }
        public string ResultViewName { get; set; }
        public List<SelectListItem> QuestionSetList { get; set; }
        public List<ResultViewItemModel> ResultViewItemModels { get; set; }
        public List<ResultViewDisplayItemModel> ResultViewDisplayItemModels { get; set; }
        public List<ResultViewShareModel> ResultViewShareModels { get; set; }
        public List<SelectListItem> QuestionList { get; set; }
        public List<SelectListItem> EvaluationTypes { get; set; }
        public List<SelectListItem> CompaniesList { get; set; }
        public ResultViewEditModel()
        {
            QuestionSetList = new List<SelectListItem>();
            ResultViewItemModels = new List<ResultViewItemModel>();
            ResultViewDisplayItemModels = new List<ResultViewDisplayItemModel>();
            ResultViewShareModels = new List<ResultViewShareModel>();
            QuestionList = new List<SelectListItem>();
            EvaluationTypes = new List<SelectListItem>();
            CompaniesList = new List<SelectListItem>();
        }

        public ScreenType ScreenType { get; set; }
    }

    public class ResultViewItemModel
    {
        public Guid ResultViewId { get; set; }
        public Guid ResultViewItemId { get; set; }
        public Guid QuestionId { get; set; }
        public ViewEvalutionType ViewEvalutionType { get; set; }
        public string QuestionText { get; set; }
        public List<SelectListItem> QuestionList { get; set; }
        public List<SelectListItem> EvaulationTypes  { get; set; }
        public string ExpressionValue { get; set; }

        public ResultViewItemModel()
        {
            QuestionList = new List<SelectListItem>();
        }

    }

    public class ResultViewDisplayItemModel
    {
        public Guid ResultViewId { get; set; }
        public Guid ResultViewDisplayItemID { get; set; }
        public Guid QuestionId { get; set; }
        public string QuestionText { get; set; }

    }

    public class ResultViewShareModel
    {
        public Guid ResultViewId { get; set; }
        public Guid ResultViewShareId { get; set; }
        public string CompanyName { get; set; }
        public Guid CompanyId { get; set; }
    }
}

mobi.QualityControl/mobi.QualityControl.Web/ViewModels/Results/ResultViewIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mobi.QualityControl.Web.ViewModels.Results
{
    public class ResultViewIndexModel
    {
        public ResultViewIndexModel()
        {
            ResultViewIndexItems = new List<ResultViewIndexItem>();
            ResultViewSharedIndexItems = new List<ResultViewSharedIndexItem>();
        }
        public List<ResultViewIndexItem> ResultViewIndexItems { get; set; }
        public List<ResultViewSharedIndexItem> ResultViewSharedIndexItems { get; set; }
    }

    public class ResultViewIndexItem
    {
        public Guid ResultViewId { get; set; }
        public string ResultViewName { get; set; }
        public int TransactionCount { get; set; }
    }

    public class ResultViewSharedIndexItem
    {
        public Guid ResultViewId { get; set; }
        public string ResultViewName { get; set; }
        public int TransactionCount { get; set; }
    }
}

mobi.QualityControl/mobi.QualityControl.Web/ViewModels/Results/TransactionSetResultModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Mobi.QualityControl.Web.ViewModels.Results
{
    public class TransactionSetResultModel
    {
        public TransactionSetResultModel()
        {
            TransactionSetItems = new List<TransactionSetItem>();
            QuestionResultHeaders = new List<QuestionResultHeader>();
        }

        public List<QuestionResultHeader> QuestionResultHeaders { get; set; }
        public Guid QuestionSetId { get; set; }
        public string QuestionSetName { get; set; }
        public List<TransactionSetItem> TransactionSetItems { get; set; }
        public int ColumnCount { get; set; }
    }

    public class QuestionResultHeader
    {
        public Guid QuestionId { get; set; }
        public int OrderPosition { get; set; }
        public string QuestionName { get; set; }

    }

    public class TransactionSetItem
    {
        
        public TransactionSetItem()
        {
            TransactionResultItems = new List<TransactionResultItem>();
        }

        public Guid TransactionSetId { get; set; }
        public DateTime CreationDateTime { get; set; }
        public List<TransactionResultItem> TransactionResultItems { get; set; }
    }

    public class TransactionResultItem
    {
        public Guid QuestionId { get; set; }
        public string ControlType { get; set; }
        public int OrderPosition { get; set; }

        public string ResultValue { get; set; }
    }
}

mobi.QualityControl/mobi.QualityControl.Web/Controllers/ResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using log4net;
using Microsoft.Ajax.Utilities;
using Mobi.QualityControl.Framework.DataContext;
using Mobi.QualityControl.Framework.Enum;
using Mobi.QualityControl.Framework.Helpers;
using Mobi.QualityControl.Framework.Model;
using Mobi.QualityControl.Web.Helpers;
using Mobi.QualityControl.Web.Models;
using Mobi.QualityControl.Web.ViewModels.Results;

namespace Mobi.QualityControl.Web.Controllers
{
    [Authorize]
    public class ResultsController : AuthenticatedController
    {
        ILog log = log4net.LogManager.GetLogger(typeof(ResultsController));

        //
        // GET: /Results/
        private QcContext context = new QcContext();

        public ActionResult Index()
        {
           
            var model = new ResultViewIndexModel();
            var resultsViewQuery = context.ResultViews.Select(o => new
            {
                o.QuestionSet.Company.CompanyId,
                o.ResultViewId,
                o.ResultViewName

            }).Where(o => o.CompanyId == AuthenticatedUser.Company.CompanyId);
            foreach (var resultView in resultsViewQuery)
            {
                model.ResultViewIndexItems.Add(new ResultViewIndexItem()
                {
                    ResultViewId = resultView.ResultViewId,
                    ResultViewName = resultView.ResultViewName,
                });

            }
            var relationshipResults = context.ResultViewShares.Select(o => new
            {
                o.Company.CompanyId,
                o.ResultView.ResultViewId,
                o.ResultView.ResultViewName
            }).Where(o => o.CompanyId == AuthenticatedUser.Company.CompanyId);
            foreach (var relationshipResult in relationshipResults.ToList())
            {
                model.ResultViewSharedIndexItems.Add(new ResultViewSharedIndexItem()
                {
                    ResultViewId = relationshipResult.ResultViewId,
                    ResultViewName = relationshipResult.ResultViewName,
                });
            }

            return View(model);
        }

        public ActionResult ResultsSharesForCompany(Guid id)
        {
            var model = new ResultViewIndexModel();
            var relationshipResults = context.ResultViewShares.Select(o => new
            {
                o.Company.CompanyId,
               ResultViewCompanyId = o.ResultView.QuestionSet.Company.CompanyId,
               o.ResultView.ResultViewId,
               o.ResultView.ResultViewName
            }).Where(o => o.CompanyId == AuthenticatedUser.Company.CompanyId && o.ResultViewCompanyId == id);
            foreach (var relationshipResult in relationshipResults.ToList())
            {
                model.ResultViewSharedIndexItems.Add(new ResultViewSharedIndexItem()
                {
                    ResultViewId = relationshipResult.ResultViewId,
                    ResultViewName = relationshipResult.ResultViewName,
                });
            }

            return View(model);


        }

        public ActionResult Create(Guid? questionSetId)
        {
            var model = new ResultViewEditModel();
            model.ScreenType = ScreenType.Create;
            if (questionSetId != null)
            {
                model.QuestionSetId = (Guid)questionSetId;
                model.QuestionSetName = context.QuestionSets.Select(o => new
                {
                    o.QuestionSetId,
                    o.QuestionSetName
                    }).FirstOrDefault(o => o.QuestionSetId == model.QuestionSetId).QuestionSetName;
            }
            else
            {
                model.QuestionSetList = new DropDownHelper().GetQuestionSetDropDown(AuthenticatedUser.Company.CompanyId);
            }


            return View("Edit", model);
        }

        public ActionResult Details(Guid id)
        {
            var model = new ResultViewEditModel();
            model.ScreenType = ScreenType.Details;
            PopulateEditModel(id, model);
           return View("Edit", model);
            
        }

        public ActionResult Edit(Guid id)
        {
            var model = new ResultViewEditModel();
            model.ScreenType = ScreenType.Edit;
            PopulateEditModel(id, model);

            return View(model);

        }

        [HttpPost]
        public ActionResult Edit(ResultViewEditModel model)
        {
            ResultView resultView;
            if (model.ScreenType == ScreenType.Create)
            {
                resultView = new ResultView();
                resultView.ResultViewId = Guid.NewGuid();
                resultView.QuestionSet = context.QuestionSets.FirstOrDefault(o => o.QuestionSetId == model.QuestionSetId);
            }
            else
            {
                resultView = context.ResultViews.FirstOrDefault(o => o.ResultViewId == model.ResultViewId && o.QuestionSet.Company.CompanyId == this.AuthenticatedUser.Company.CompanyId);
            }
            resultView.ResultViewName = model.ResultViewName;

            if (model.ScreenType == ScreenType.Create)
            {

                context.ResultViews.Add(resultView);

            }
            context.SaveChanges();
            TempData["SuccessMessage"] = "The Result View has been successfully updated.";
            return RedirectToAction("Edit", new { id = resultView.ResultViewId });
        }


        [HttpPost]
        public ActionResult AddRule(ResultViewItemModel model)
        {
            var resultViewItem = new ResultViewItem();
            resultViewItem.ResultViewItemId = Guid.NewGuid();
            resultViewItem.Question = context.Questions.FirstOrDefault(o => o.QuestionId == model.QuestionId);
            resultViewItem.ExpressionValue = model.ExpressionValue;
            resultViewItem.ViewEvalutionType = model.ViewEvalutionType;
            var resultView = context.ResultViews.FirstOrDefault(o => o.ResultViewId == model.ResultViewId);
            resultView.ResultViewItems.Add(resultViewItem);
            
            context.SaveChanges();
            return RedirectToAction("Edit", new { id = model.ResultViewId });
        }

        [HttpPost]
        public ActionResult AddDisplayColumn(ResultViewDisplayItemModel model)
        {
            var resultViewDisplayItem = new ResultViewDisplayItem();
            resultViewDisplayItem.ResultViewDisplayItemId = Guid.NewGuid();
            resultViewDisplayItem.Question = context.Questions.FirstOrDefault(o => o.QuestionId == model.QuestionId);
            var resultView = context.ResultViews.FirstOrDefault(o => o.ResultViewId == model.ResultViewId);
            resultView.ResultViewDisplayItems.Add(resultViewDisplayItem);

            context.SaveChanges();
            return RedirectToAction("Edit", new { id = model.ResultViewId });
        }


        [HttpPost]
        public ActionResult AddCompanyShareView(ResultViewShareModel model)
        {
            var resultViewShare = new ResultViewShare();
            resultViewShare.ResultViewShareId = Guid.NewGuid();
            resultViewShare.Company = context.Companies.FirstOrDefault(o => o.CompanyId == model.CompanyId);
            resultViewShare.ResultView = context.ResultViews.FirstOrDefault(o => o.ResultViewId == model.ResultViewId);
            context.ResultViewShares.Add(resultViewShare);
            context.SaveChanges();
            return RedirectToAction("Edit", new { id = model.ResultViewId });

        }



        private void PopulateEditModel(Guid id, ResultViewEditModel model)
        {
            var resultViewQuery = context.ResultViews.Select(o => new
            {
                o.ResultViewId,
                o.QuestionSet.Company.CompanyId,
                o.QuestionSet.QuestionSetName,
                o.QuestionSet.QuestionSetId,
                o.ResultViewName,
                ResultViewItems = o.ResultViewItems.Select(rvi => new
                {
                    rvi.ResultViewItemId,
                    rvi.Question.QuestionText,
                    rvi.ViewEvalutionType,
                    rvi.ExpressionValue

                }),
                ResultViewDisplayItems = o.ResultViewDisplayItems.Select(rvd => new
                {
                    rvd.Question.QuestionId,
                    rvd.Question.QuestionText,
                    rvd.ResultViewDisplayItemId
                }),
                ResultViewShares = o.ResultViewShares.Select(rvs => new
                {
                    rvs.Company.CompanyId,
                    rvs.Company.CompanyName,
                    rvs.ResultView.ResultViewId,
                    rvs.ResultViewShareId
                })
            }).FirstOrDefault(o => o.ResultViewId == id && o.CompanyId == AuthenticatedUser.Company.CompanyId);
            if (resultViewQuery != null)
            {
                model.ResultViewName = resultViewQuery.ResultViewName;
                model.QuestionSetName = resultViewQuery.QuestionSetName;
                model.QuestionSetId = resultViewQuery.QuestionSetId;
                model.ResultViewId = resultViewQuery.ResultViewId;
                model.QuestionList = new DropDownHelper().GetQuestionDropDown(AuthenticatedUser.Company.CompanyId, model.QuestionSetId);
                model.EvaluationTypes = new DropDownHelper().GetViewEvalutionDropDown();
                model.CompaniesList = new DropDownHelper().GetAllRelationshipResultCompaniesDropDown(AuthenticatedUser.Company.CompanyId,id);

                foreach (var resultViewItem in resultViewQuery.ResultViewItems)
                {

mobi.QualityControl/mobi.QualityControl.Web/Views/Results/Index.cshtml
@model Mobi.QualityControl.Web.ViewModels.Results.ResultViewIndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}

<!-- Heading -->
<div class="page-title">
    <a href="@Url.Action("Index","Dashboard")"><i class="icon-custom-left"></i></a>
    <h3>Result Views</h3>
    <div class="buttons pull-right">
        <a href="@Url.Action("Create", "Results", new { area = "" })" class="btn btn-primary btn-icon glyphicons circle_plus"><i></i>Add Result View</a>
    </div>
    <div class="clearfix"></div>
</div>

<div class="row-fluid">
    <div class="span12">
        <div class="grid simple ">
            <div class="grid-title">
                <h4>Table <span class="semi-bold">Result Views</span></h4>
                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            <div class="grid-body ">
                @if (Model.ResultViewIndexItems.Count > 0)
                {

                    <table class="table table-hover table-condensed">
                        <thead>
                            <tr>

                                <th>
                                    Results Views
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ResultViewIndexItems)
                            {
                                <tr class="selectable">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ResultViewName)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Details", "Results", new {area = "", id = item.ResultViewId})" class=" btn btn-primary btn-sm .btn-small ">View</a>

                                        <a href="@Url.Action("Delete", "Results", new {area = "", id = item.ResultViewId})" class=" btn btn-sm .btn-small btn-danger">Delete</a>
                                        
                                        <a href="@Url.Action("ResultView", "Results", new { area = "", id = item.ResultViewId })" class=" btn btn-sm .btn-small btn-info">View Transactions</a>
                                        
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert">
                        <button class="close" data-dismiss="alert"></button>
                        No Result Views Exist
                    </div>
                }

            </div>
        </div>
        
        
        <div class="grid simple ">
            <div class="grid-title">
                <h4>Table <span class="semi-bold">Shared Result Views</span></h4>
                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            <div class="grid-body ">
                @if (Model.ResultViewSharedIndexItems.Count > 0)
                {

                    <table class="table table-hover table-condensed">
                        <thead>
                            <tr>

                                <th>
                                    Shared Results Views
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ResultViewSharedIndexItems)
                            {
                                <tr class="selectable">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ResultViewName)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("ResultView", "Results", new { area = "", id = item.ResultViewId })" class=" btn btn-sm .btn-small btn-info">View Transactions</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert">
                        <button class="close" data-dismiss="alert"></button>
                        No Result Views Exist
                    </div>
                }

            </div>
        </div>
    </div>
</div>

mobi.QualityControl/mobi.QualityControl.Web/Views/Results/ResultsSharesForCompany.cshtml
model Mobi.QualityControl.Web.ViewModels.Results.ResultViewIndexModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}

<!-- Heading -->
<div class="page-title">
    <a href="@Url.Action("Index","Dashboard")"><i class="icon-custom-left"></i></a>
    <h3>Result Views</h3>

    <div class="clearfix"></div>
</div>
<div class="row-fluid">
    <div class="span12">
        <div class="grid simple ">
            <div class="grid-title">
                <h4>Table <span class="semi-bold">Shared Result Views</span></h4>
                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            <div class="grid-body ">
                @if (Model.ResultViewSharedIndexItems.Count > 0)
                {

                    <table class="table table-hover table-condensed">
                        <thead>
                            <tr>

                                <th>
                                    Shared Results Views
                                </th>

                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ResultViewSharedIndexItems)
                            {
                                <tr class="selectable">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ResultViewName)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("ResultView", "Results", new { area = "", id = item.ResultViewId })" class=" btn btn-sm .btn-small btn-info">View Transactions</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert">
                        <button class="close" data-dismiss="alert"></button>
                        No Result Views Exist
                    </div>
                }

            </div>
        </div>
    </div>
</div>

mobi.QualityControl/mobi.QualityControl.Web/Views/Results/ViewAllForQuestionSet.cshtml
@model Mobi.QualityControl.Web.ViewModels.Results.TransactionSetResultModel
@{
    ViewBag.Title = "ViewAllForQuestionSet";
    Layout = "~/Views/Shared/_AppLayout.cshtml";
}

<!-- Heading -->
<div class="page-title">
    <a href="@Url.Action("Index","Dashboard")">
        <i class="icon-custom-left"></i>
    </a>
    <h3>Results</h3>

    <div class="clearfix"></div>
</div>

<!-- // Heading END -->

<div class="row-fluid">
    <div class="span12">
        <div class="grid simple ">
            <div class="grid-title">
                <h4>Table <span class="semi-bold">Question Set</span></h4>
                <div class="tools"> <a href="javascript:;" class="collapse"></a> <a href="#grid-config" data-toggle="modal" class="config"></a> <a href="javascript:;" class="reload"></a> <a href="javascript:;" class="remove"></a> </div>
            </div>
            <div class="grid-body ">
                <table class="table table-hover table-condensed" id="example">
                    <thead>
                        <tr>
                            @foreach (var questionHeader in Model.QuestionResultHeaders.OrderBy(o => o.OrderPosition))
                            {
                                <th>@questionHeader.QuestionName</th>
                            }


<th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var transactionSetItem in Model.TransactionSetItems)
                        {
                            <tr class="selectable">
                                @foreach (var questionHeader in Model.QuestionResultHeaders.OrderBy(o => o.OrderPosition))
                                {

                                    var questionTrans = transactionSetItem.TransactionResultItems.FirstOrDefault(o => o.QuestionId == questionHeader.QuestionId);
                                    if (questionTrans != null)
                                    {
                                        <td> @questionTrans.ResultValue</td>
                                    }
                                    else
                                    {
                                        <td> </td>
                                    }

                                }

                                <td>
                                    <a href="@Url.Action("View", "Transaction", new { area = "", id = transactionSetItem.TransactionSetId })" class=" btn btn-primary btn-sm .btn-small ">View</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>


            </div>
        </div>
    </div>
</div>